name: Heart Disease ML Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t heart-disease-ml .

      - name: Run ML pipeline
        run: docker run heart-disease-ml
